#!/usr/bin/env python3
"""Update golden test fixtures with real APNs from loaded data."""
import json
import sys
from pathlib import Path
from typing import List, Dict, Any


def extract_apns_from_data(data_path: Path, apn_field: str = "APN") -> List[str]:
    """Extract APNs from parcel GeoJSON."""
    with open(data_path) as f:
        data = json.load(f)
    
    apns = []
    for feature in data.get("features", []):
        props = feature.get("properties", {})
        apn = props.get(apn_field) or props.get(apn_field.lower())
        if apn:
            apns.append(str(apn))
    
    return sorted(list(set(apns)))[:20]  # Return up to 20 unique APNs


def create_golden_test(apn: str, expected_output: Dict[str, Any], output_dir: Path, index: int):
    """Create a golden test file."""
    output_file = output_dir / f"{index:03d}.apn.json"
    
    # Ensure all required fields
    golden = {
        "apn": apn,
        "jurisdiction": expected_output.get("jurisdiction", "Austin, TX"),
        "zone": expected_output.get("zone", "UNKNOWN"),
        "setbacks_ft": expected_output.get("setbacks_ft", {
            "front": 0, "side": 0, "rear": 0, "street_side": 0
        }),
        "height_ft": expected_output.get("height_ft", 0),
        "far": expected_output.get("far", 0),
        "lot_coverage_pct": expected_output.get("lot_coverage_pct", 0),
        "overlays": expected_output.get("overlays", []),
        "sources": expected_output.get("sources", []),
        "notes": expected_output.get("notes", ""),
        "run_ms": 0
    }
    
    with open(output_file, 'w') as f:
        json.dump(golden, f, indent=2)
    
    return output_file


def update_golden_tests(parcel_data_path: str, golden_outputs: List[Dict[str, Any]], 
                       output_dir: str = "tests/golden"):
    """Update golden test fixtures with real data."""
    parcel_path = Path(parcel_data_path)
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    if not parcel_path.exists():
        raise FileNotFoundError(f"Parcel data not found: {parcel_data_path}")
    
    # Extract APNs
    print(f"Extracting APNs from {parcel_path}...")
    apns = extract_apns_from_data(parcel_path)
    print(f"Found {len(apns)} unique APNs")
    
    if len(apns) < len(golden_outputs):
        print(f"Warning: Only {len(apns)} APNs found, but {len(golden_outputs)} outputs provided")
        apns = apns * ((len(golden_outputs) // len(apns)) + 1)
        apns = apns[:len(golden_outputs)]
    
    # Create golden test files
    print(f"Creating {len(golden_outputs)} golden test files...")
    created_files = []
    for i, (apn, expected) in enumerate(zip(apns, golden_outputs), 1):
        output_file = create_golden_test(apn, expected, output_path, i)
        created_files.append(output_file)
        print(f"  Created: {output_file.name} (APN: {apn})")
    
    print(f"\n✓ Created {len(created_files)} golden test files in {output_path}")
    return created_files


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: update_golden_tests.py <parcel_data_path> [output_dir]")
        print("\nExample:")
        print("  python3 scripts/update_golden_tests.py data/austin/parcels.geojson")
        print("\nNote: This creates placeholder golden tests. Run CLI to generate actual outputs:")
        print("  for apn in $(jq -r '.apn' tests/golden/*.json | head -5); do")
        print("    python3 zoning.py --apn $apn --city austin --out /tmp/$apn.json")
        print("  done")
        sys.exit(1)
    
    parcel_path = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "tests/golden"
    
    # For now, create placeholder golden tests
    # In production, these would be generated by running the CLI
    placeholder_outputs = [{
        "jurisdiction": "Austin, TX",
        "zone": "SF-3",
        "setbacks_ft": {"front": 25, "side": 5, "rear": 10, "street_side": 0},
        "height_ft": 35,
        "far": 0.4,
        "lot_coverage_pct": 40,
        "overlays": [],
        "sources": [{"type": "map", "cite": "austin_zoning_v2024"}],
        "notes": "",
        "run_ms": 0
    }] * 20
    
    try:
        update_golden_tests(parcel_path, placeholder_outputs, output_dir)
        print("\n⚠ Note: These are placeholder golden tests.")
        print("   Run the CLI with real APNs to generate actual expected outputs.")
    except Exception as e:
        print(f"✗ Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()

